export type PublicSettingsDto = {
  registrationEnabled: boolean;
  initialRegisterCredits: number;
  inviteRegisterInviterCredits: number;
  inviteRegisterInviteeCredits: number;
  invitePaymentCreditsPerYuan: number;
  siteTitle: string;
  siteIcon: string;
  siteFooter: string;
  homeTopMarqueeText: string;
  startupPopupType: 'image' | 'html';
  startupPopupImageUrl: string;
  startupPopupHtml: string;
  startupPopupTargetUrl: string;
  startupPopupWidthPx: number;
  startupPopupHeightPx: number;
  cardPurchaseUrl: string;
  aboutUs: string;
  privacyPolicy: string;
  termsOfService: string;
  themeColor: string;
  turnstileEnabled: boolean;
  turnstileSiteKey: string;
  wechatPayEnabled: boolean;
  creditBuyEnabled: boolean;
  creditBuyRatePerYuan: number;
  creditBuyMinCredits: number;
  creditBuyMaxCredits: number;
  chatFileUploadEnabled: boolean;
  chatFileMaxFilesPerMessage: number;
  chatFileMaxFileSizeMb: number;
  chatFileAllowedExtensions: string;
  chatFileMaxExtractChars: number;
  chatFileContextMode: 'full' | 'retrieval';
  chatFileRetrievalTopK: number;
  chatFileChunkSize: number;
  chatFileChunkOverlap: number;
  chatFileRetrievalMaxChars: number;
  webSearchEnabled: boolean;
  webSearchBaseUrl: string;
  webSearchMode: 'off' | 'auto' | 'always';
  webSearchLanguage: string;
  webSearchCategories: string;
  webSearchSafeSearch: number;
  webSearchTimeRange: '' | 'day' | 'week' | 'month' | 'year';
  webSearchTopK: number;
  webSearchTimeoutMs: number;
  webSearchBlockedDomains: string;
};
